baseURL = "/"
languageCode = "en-us"
title = "DetectionLab"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Author of the site, will be used in meta information
  author = "clong"
  # Description of the site, will be used in meta information
  description = "DetectionLab Documentation"
  themeVariant = "clong"
  disableInlineCopyToClipBoard = true

[[deployment.targets]]
# An arbitrary name for this target.
name = "detectionlab"
URL = "s3://detectionlab.network?region=us-west-1"

[[menu.shortcuts]]
name = "<i class='fab fa-twitter'></i> DetectionLab Twitter"
url = "https://twitter.com/intent/follow?screen_name=detectionlab"
weight = 1

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> DetectionLab Github"
url = "https://github.com/clong/detectionlab"
weight = 2

[[menu.shortcuts]]
name = "<i class='fab fa-slack'></i> DetectionLab Slack"
url = "https://join.slack.com/t/detectionlab/shared_invite/zt-mv1qnw9f-3qo2ZrB0IbIKhvinfsgYhg"
weight = 3